In [2]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[10,-20,30,-40],[50,-60,70,-80]])

relu 함수와 덧셈은 원소별 연산이다. 따라서 텐서의 각 원소에 독립적으로 적용된다.
relu 함수는 각 원소에 대해 원소의 값이 0보다 작을 경우 해당 원소 값을 0으로 바꾼다.

In [3]:
def naive_relu(x):
    assert len(x.shape)==2              #x는 2D 넘파이 배열, assert는 뒤의 조건이 True가 아니면 AssertError를 발생시킴
    
    x= x.copy()                          #입력 텐서 자체를 바꾸지 않아야 함
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j]=max(x[i,j],0)
    return x

In [4]:
def naive_add(x,y):
    assert len(x.shape)==2
    assert x.shape == y.shape
    
    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

numpy는 내장 함수로 원소별 연산을 잘 수행해준다.

In [5]:
z=x+y
z=np.maximum(z,0.)

In [6]:
print(z)

[[11.  0. 33.  0.]
 [55.  0. 77.  0.]]


In [7]:
z=naive_add(x,y)

In [8]:
print(z)

[[ 11 -18  33 -36]
 [ 55 -54  77 -72]]


In [9]:
z=naive_relu(z)
print(z)

[[11  0 33  0]
 [55  0 77  0]]


### 크기가 다른 텐서끼리 더해질 때는 작은 텐서가 큰 텐서의 크기에 맞추어 브로드캐스팅을 수행한다.
1. 큰 텐서의 ndim에 맞도록 작은 텐서에 축이 추가된다.
2. 작은 텐서가 새 축을 따라서 큰 텐서의 크기에 맞도록 반복됨

In [10]:
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1]==y.shape[0]
    
    x=x.copy
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j]+=y[j]
    return x

크기가 다른 두 텐서에 브로드캐스팅으로 원소별 maximum 연산을 적용하는 예

In [11]:
a=np.random.random((64,3,32,10))
b=np.random.random((32,10))
z=np.maximum(a,b)

print(z.shape)                  #출력 z의 크기는 x와 동일함-> (64,3,32,10)
print(z)

(64, 3, 32, 10)
[[[[0.64401232 0.97060841 0.89314779 ... 0.55150152 0.42674869
    0.58255702]
   [0.71059033 0.95429108 0.68099813 ... 0.95643377 0.83507031
    0.7213562 ]
   [0.78025394 0.72093006 0.26314559 ... 0.50371363 0.81083626
    0.45445349]
   ...
   [0.74627489 0.63377375 0.93210619 ... 0.39051608 0.63235666
    0.50482266]
   [0.97614643 0.77927371 0.40981402 ... 0.79653181 0.59863465
    0.54193473]
   [0.42588257 0.59481179 0.74404059 ... 0.43377428 0.83463416
    0.89690793]]

  [[0.64401232 0.97060841 0.47372842 ... 0.55150152 0.70592978
    0.92814843]
   [0.62386122 0.61812754 0.98406542 ... 0.95643377 0.82547475
    0.7213562 ]
   [0.78025394 0.48778588 0.28708716 ... 0.39852549 0.75288075
    0.45445349]
   ...
   [0.62416482 0.3741495  0.93210619 ... 0.05234555 0.88253609
    0.50482266]
   [0.97614643 0.39701135 0.60328669 ... 0.15221322 0.91513087
    0.53461396]
   [0.73605519 0.59481179 0.68424271 ... 0.37833388 0.83463416
    0.89690793]]

  [[0.64401232 0.9

### 텐서 곱셈(텐서 점곱) 

In [16]:
# 두 벡터간의 점곱연산
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    
    z=0.
    for i in range (x.shape[0]):
        z+=x[i]*y[i]
    return z

In [18]:
x=np.array([1])
y=np.array([2])
z=naive_vector_dot(x,y)
print(z)

2.0


In [19]:
#행렬과 벡터간의 점곱
def naive_matrix_vector_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    
    z=np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i]+=x[i,j]*y[j]
    return z

In [21]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([10,20,30])
z=naive_matrix_vector_dot(x,y)
print(z)

[140. 320. 500.]


행렬간의 점곱 dot(x,y) 시에 x.shape[1]==y.shape[0] 이어야 한다. 그러면 결과는 (x.shape[0],y.shape[1])모양이 된다. 

In [26]:
#행렬간의 점곱
def naive_matrix_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==2
    assert x.shape[1]==x.shape[0]
    
    z=np.zeros((x.shape[0],y.shape[1]))
    
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x=x[i, :]
            column_y=y[:, j]
            z[i,j]=naive_vector_dot(row_x,colum_y)
    return z

### 텐서 크기 변환

In [30]:
#특정 크기에 맞게 열과 행을 재배열
x=np.array([[0., 1.],
           [2., 3.],
           [4., 5.]])
print(x.shape)

(3, 2)


In [33]:
x=x.reshape(6,1)
print(x)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [35]:
x=x.reshape((2,3))
print(x)

[[0. 1. 2.]
 [3. 4. 5.]]


#### 전치 (행과 열을 바꿈)

In [37]:
x=np.zeros((300,20))
x=np.transpose(x)
print(x.shape)

(20, 300)
